### ISSUE TITLE
Review literature for understanding merging of visual and centroidal factors with kinematic-inertial robot estimation

### ISSUE THREAD

**Issue by prashanthr05** [dic-iit/kindyn-vio#5]
**Recent works post this review**
- [VILENS: Visual, Inertial, Lidar, and Leg Odometry for All-Terrain Legged Robots](https://arxiv.org/pdf/2107.07243.pdf) 2021
- [Legged Robot State Estimation With Dynamic Contact Event Information](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9468900&casa_token=jj_a_WKKYIQAAAAA:rbM2oFafgOTXW89usxQ1cnacTlt4acP0jOsFgLemXDuJ3xHIo3J6MslZprrKt8Fr_usNzTviiao&tag=1), 2021

**Base Paper readings**
- [x] [VID-Fusion: Robust Visual-Inertial-Dynamic Odometry for Accurate External Force Estimation](https://arxiv.org/abs/2011.03993)
- [x] [VIMO: Simultaneous Visual Inertial Model-based Odometry and Force Estimation](https://ieeexplore.ieee.org/document/8721075) Code: https://github.com/uzh-rpg/vimo
- [x] [VINS-MONO: A Robust and Versatile Monocular Visual-Inertial State Estimator](https://ieeexplore.ieee.org/document/8421746) Code: https://github.com/HKUST-Aerial-Robotics/VINS-Mono
- [x] [Contact forces pre-integration for the whole body estimation of legged robots](https://hal.archives-ouvertes.fr/hal-02991717)
- [x] [Unified Multi-Modal Landmark Tracking for Tightly Coupled Lidar-Visual-Inertial Odometry](https://arxiv.org/abs/2011.06838)
- [x] [IMU Preintegration on Manifold for Efficient Visual-Inertial Maximum-a-Posteriori Estimation](https://arxiv.org/abs/1512.02363)
- [x] [Factor graphs for Robot Perception](http://www.cs.cmu.edu/~kaess/pub/Dellaert17fnt.pdf) (long read but quite an useful tool)
- [x] [Hybrid Contact Preintegration for Visual-Inertial-Contact State Estimation Using Factor Graphs](https://arxiv.org/pdf/1803.07531.pdf)
- [x] [Legged Robot State-Estimation Through Combined Forward Kinematic and Preintegrated Contact Factors](https://arxiv.org/pdf/1712.05873.pdf)
- [x] [Robust Legged Robot State Estimation using Factor Graph Optimization](https://arxiv.org/pdf/1904.03048.pdf)
- [x] [Absolute humanoid localization and mapping based on IMU Lie group and fiducial markers](https://hal.archives-ouvertes.fr/hal-02183498/file/Fourmy_19_Humanoids.pdf)
- [x] [Preintegrated Velocity Bias Estimation to Overcome Contact Nonlinearities in Legged Robot Odometry](https://ori.ox.ac.uk/media/5602/2020icra_wisth.pdf)

**iSAM2 Background**
- [iSAM2: Incremental Smoothing and Mapping Using the Bayes Tree](https://www.cs.cmu.edu/~kaess/pub/Kaess12ijrr.pdf)

**Supplementary readings**
- [High Accuracy Preintegration for Visual-Inertial Navigation](http://udel.edu/~pgeneva/downloads/papers/c01.pdf)
-  [Associating Uncertainty With Three-Dimensional Poses for Use in Estimation Problems](https://ieeexplore.ieee.org/document/6727494)
- [Online Variational Bayesian Motion Averaging](https://hal.archives-ouvertes.fr/hal-01718015/document)
-  [An Invariant-EKF VINS Algorithm for Improving Consistency](https://arxiv.org/abs/1702.07920)
-  [A Multi-State Constraint Kalman Filter for Vision-aided Inertial Navigation](https://ieeexplore.ieee.org/document/4209642)
-  [Fusion of Optical Flow and Inertial Measurements for Robust Egomotion Estimation](https://ieeexplore.ieee.org/document/6942991)
-  [A Factor Graph Approach to Estimation and Model Predictive Control on Unmanned Aerial Vehicles](https://ieeexplore.ieee.org/document/6842254)
-  [An Analytical Solution to the IMU Initialization Problem for Visual-Inertial Systems](https://arxiv.org/abs/2103.03389) Code: https://github.com/dzunigan/imu_initialization

**Comment by GiulioRomualdi** [comment]
Another interesting resource is https://gtsam.org/2019/09/18/legged-robot-factors-part-I.html
In this example factor graph optimization is used to estimate the base and the contacts of a bipedal robot
